### ISSUE TITLE
feature: provide some feedback after triggering a workflow

### ISSUE THREAD

**Issue by jeremyd2019** [msys2-arm/msys2-autobuild-controller#12]
Requested by @Biswa96.  Was thinking just adding a generic `flash` message after triggering, since there is *no* feedback from github apis that might be helpful, and that kind of matches what github itself does on their actions page.  I never wrote this down because it would probably only be a line or two of code, but I never did get around to actually doing it, so recording it so it doesn't get forgotten.

**Comment by jeremyd2019** [comment]
What github's "flash" message looks like:
![image](https://user-images.githubusercontent.com/4524874/209864093-6a8ef4bb-f587-4701-b742-3f46589703e6.png)


Entirely devoid of useful information, but that's all you can tell from the API result.  It doesn't even return the ID of the run created so you can query what it's doing.

**Comment by lazka** [comment]
https://flask.palletsprojects.com/en/2.2.x/patterns/flashing/
